# Generated by Django 3.0.6 on 2021-01-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=55)),
                ('desc', models.TextField()),
            ],
        ),
    ]
